### ISSUE TITLE
Command timed out after 60000 milliseconds: unoconvert

### ISSUE THREAD

**Issue by joebordes** [lynxtaa/unoserver-web#11]
Hi

I am seeing a timeout error a few times a day.
This is the command I used to start the service

`docker run -d --name gendocpdf --restart always lynxtaa/unoserver-web:latest`

then I call the service from PHP using PHP-Curl. A few times a day it fails with the error:

```
{"level":50,"reqId":"req-2w","req":{"method":"POST","url":"/convert/pdf","hostname":"gendocpdf:3000","remoteAddress":"172.17.0.1","remotePort":52974},
"res":{"statusCode":500},
"err":{"type":"Error","message":"Command timed out after 60000 milliseconds: unoconvert --port 12345 /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.odt /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.pdf\nTimed out",
"stack":"Error: Command timed out after 60000 milliseconds: unoconvert --port 12345 /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.odt /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.pdf\nTimed out
    at timeoutKill (file:///app/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/kill.js:60:23)
    at Timeout._onTimeout (file:///app/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/kill.js:72:4)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)",
"timedOut":true,"signal":"SIGTERM","originalMessage":"Timed out",
"shortMessage":"Command timed out after 60000 milliseconds: unoconvert --port 12345 /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.odt /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.pdf\nTimed out",
"command":"unoconvert --port 12345 /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.odt /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.pdf",
"escapedCommand":"unoconvert --port 12345 \"/tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.odt\" \"/tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.pdf\"",
"signalDescription":"Termination","stdout":"","stderr":"","cwd":"/app","failed":true,"isCanceled":false,"killed":false,"attemptNumber":4,"retriesLeft":0},
"msg":"Command timed out after 60000 milliseconds: unoconvert --port 12345 /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.odt /tmp/upload-a8dda965-e061-425c-8b54-15e8472c868c/file.pdf\nTimed out"}
{"level":30,"reqId":"req-2w","res":{"statusCode":500},"responseTime":247071.43800735474,"msg":"request completed"}
```

and I am forced to restart the container to get it working again.

Any idea of what may be happening or what I may change to avoid the error?

Thanks

**Comment by lynxtaa** [comment]
Hi 

I'm not sure why this could happen. It runs [unoconvert](https://github.com/unoconv/unoserver) under the hood and it fails to complete in 60 seconds. Maybe reducing number of workers may help (MAX_WORKERS env variable).

I've just published a newer version [0.7.0](https://hub.docker.com/layers/lynxtaa/unoserver-web/0.7.0/images/sha256-aeff70cf27fc801f4845fa793699d6dddb31c5efb7510883fa947fcfb803c47b?context=explore) with Ubuntu 24.04 LTS, it may also help

**Comment by joebordes** [comment]
Thanks. Let me give it a try and get back to you. :-)

**Comment by dcamarasa** [comment]
We also ran into the same issue while doing some load tests in our application. We still need to figure out the root cause.

We'll post some info here if we find any issue with unoserver.

**Comment by joebordes** [comment]
Hi

I haven't tried the timeout change but that looks very interesting and should work. I understand that it is what we were doing with the cron check and docker restart but well done from inside the service.

But everything is working correctly with your initial change. Since we pulled in that change the service has been running with no stop for 7 days and over 700 conversions.

Thanks!

**Comment by lynxtaa** [comment]
Glad to hear it!
