### ISSUE TITLE
everything works fine but the memory never get relased?

### ISSUE THREAD

**Issue by gowy222** [lynxtaa/unoserver-web#4]
Hi, 
Thx to the docker image! 
I was looking this for a longgggg time tho...

`docker run -d --name="unc" --restart=unless-stopped --net host lynxtaa/unoserver-web:latest`

then  I opened http://127.0.0.1:3000/documentation/static/index.html to test some files, everything works fine, except that the memory is not automatically freed.

I guess : uploaded files have been saved in the tmp directory(in memory in docker)? Not automatically deleted after done?
any help?

**Comment by gowy222** [comment]
and one more thing: 
is there any Ping api? can used in K8S for pod Health checks

**Comment by lynxtaa** [comment]
Hi! 

We're keeping unoserver in memory which keeps Libreoffice running for faster conversions, it explains the increase in memory. But the memory should not grow: all artifacts/uploaded files are deleted after conversion.

> is there any Ping api?

No, there isn't at the moment but you could try pinging the swagger ui: `/documentation/static/index.html`

**Comment by gowy222** [comment]
@lynxtaa 
it looks relased memory after 1.5-2 hours (fully no income request)... 
any idea to make this sooner?

**Comment by lynxtaa** [comment]
We could kill `unoserver` when no requests were made within a certain time window.

But current solution which keeps the `unoserver` always running is battle tested in production and I'm afraid this change could compromise the stability because it would be hard to debug all the race conditions: for example, when we're stopping the `unoserver` and have a new request at the same time.

**Comment by gowy222** [comment]
@lynxtaa 
FROM ubuntu:22.04 + libreoffice >=7.5.1 the memory is under control! 
I tested the loop 200 -400 times to request conversions and the memory is basically stable and doesn't go up all the time(huge better).

ps: 

Its also recommended to update nodejs dependencies （I did try once.. but @fastify/swagger 8.0+ get ts type err）

and Dockerfile may need some changes:

ignore -> add-apt-repository ppa:libreoffice/ppa  // I got net err..

pnpm config set registry https://registry.npmmirror.com   //.org => has err if dependencies too new

pnpm install --prefer-offline   // --offline => I got err... missing package

**Comment by lynxtaa** [comment]
Thanks! I've upgraded NodeJS, all the deps, Ubuntu and LibreOffice. Please check out unoserver-web:0.4.0 https://hub.docker.com/r/lynxtaa/unoserver-web/tags
