### ISSUE TITLE
How to set image DPI to improve image quality

### ISSUE THREAD

**Issue by yknext** [lynxtaa/unoserver-web#7]
This is a beautiful and neat project, thanks

When using java before, you can define the dpi, how to define the dpi of jpg to improve the image quality here, it looks a bit blurry now

**Comment by lynxtaa** [comment]
Hi! I'm using https://github.com/unoconv/unoserver under the hood and it looks like it doesn't support any DPI options unfortunately. 

You could use unoserver-web to convert office files to pdfs and then use ImageMagick (or other image converters which support pdf format) to convert pdfs to images
